### ISSUE TITLE
How to solve java.lang.ClassNotFoundException for ITK programs using SCIFIOImageIO

### ISSUE THREAD

**Issue by romangrothausmann** [scifio/scifio-imageio#38]
I got ITK-4.12.2 compiled with `Module_SCIFIO = ON` and `BUILD_TESTING = ON`. `bin/SCIFIOTestDriver` is there but if I try to execute it it fails with:
```
reader->GetUseStreaming(): 1
done checking streaming usage
ITK test driver caught an ITK exception:

itk::ExceptionObject (0x55fd2ddc0b50)
Location: "unknown" 
File: /opt/compilation/ITK_build/Modules/Remote/SCIFIO/src/itkSCIFIOImageIO.cxx
Line: 180
Description: itk::ERROR: SCIFIOImageIO(0x55fd2ddb2970): SCIFIOImageIO exited abnormally. Exception in thread "main" java.lang.NoClassDefFoundError: io/scif/itk/SCIFIOITKBridge
Caused by: java.lang.ClassNotFoundException: io.scif.itk.SCIFIOITKBridge
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: io.scif.itk.SCIFIOITKBridge.  Program will exit.
```
After installation, there is `/opt/itk-4.12.2/lib/jars/scifio-itk-bridge.jar` but setting `CLASSPATH=/opt/itk-4.12.2/lib/jars/` does not help nor `ITK_AUTOLOAD_PATH`. How should ITK-programs be told where to look for `SCIFIOITKBridge`?

**Comment by ctrueden** [comment]
That's weird; it should "just work." I tested today on my (macOS High Sierra) system, and it worked as written in the README, with no extra configuration.

Admittedly, I didn't "make install" afterward; I just used `ccmake` followed by `make` and finally `bin/SCIFIOTestDriver itkSCIFIOImageInfoTest "256 192 2 3 5"`.

Are your JAR files well formed? `jar tf /opt/itk-4.12.2/lib/jars/scifio-itk-bridge.jar`. There should also be a much larger `bioformats_package.jar` in that same folder.

**Comment by romangrothausmann** [comment]
I finally got it working by re-cloning ITK and starting over with an empty build-dir. I think the problem arose from a previously configured build-dir where I just changed `Module_SCIFIO = ON` and `BUILD_TESTING = ON` with `ccmake` and ran `make clean` before `make`. Could it be, that  `make clean` is not sufficient in some cases?

**Comment by ctrueden** [comment]
@romangrothausmann Glad to hear it!

I am not sure about behavior of `make clean`—maybe @fbudin69500 or @thewtex would have more insight into that.

In any case, I'll close this issue since it sounds like all is well now.

**Comment by fbudin69500** [comment]
Glad that it works now. I solved install problems with SCIFIO about a year ago, so it should work :)
The `make clean` command maybe doesn't remove everything that should be removed. This could be due to the `add_custom_command()` call. Maybe we could check what happens and call `set_directory_properties()` with `ADDITIONAL_MAKE_CLEAN_FILES`.

**Comment by thewtex** [comment]
> insight (ba dum ching!)

:smiley:
