### ISSUE TITLE
Update bundled JVM

### ISSUE THREAD

**Issue by thewtex** [scifio/scifio-imageio#55]
Update bundled JVM to a newer version that will bring security and performance improvements and work with the latest bioformats library.

@ctrueden any suggestions on what to use?

**Comment by ctrueden** [comment]
@thewtex Sorry for the delay in reply—just catching up now after being on vacation.

Right now, ImageJ and Fiji still run best on Java 8. We are working toward an across-the-board upgrade to Java 11, but there are a couple of obstacles, which are in the process of being addressed. Happy to link to more detailed issues if you have time and interest to follow more closely.

So at the moment I'd recommend the latest OpenJDK8. There are several different well-supported builds out there; one I like a lot is [AdoptOpenJDK](https://adoptopenjdk.net/); another is [Zulu](https://www.azul.com/downloads/zulu-community/).

**Comment by thewtex** [comment]
Awesome @ctrueden , thanks for the pointers!

**Comment by romangrothausmann** [comment]
Just a pointer to a related issue:
https://discourse.itk.org/t/scifio-java-version-limitations/
