### ISSUE TITLE
Download site no longer available

### ISSUE THREAD

**Issue by hjmjohnson** [scifio/scifio-imageio#63]
Object
  SHA512=0f278b8a9be5364d001f4fcd93c65d8bbd2fc4ac3bce8101e9fbb19a2999a36ece09002d18bced064a619c7193679586e5f35f437895580a6a22398613fb8efc
  not found at:

    https://insightsoftwareconsortium.github.io/ITKTestingData/SHA512/0f278b8a9be5364d001f4fcd93c65d8bbd2fc4ac3bce8101e9fbb19a2999a36ece09002d18bced064a619c7193679586e5f35f437895580a6a22398613fb8efc ("HTTP response code said error")
    https://data.kitware.com:443/api/v1/file/hashsum/SHA512/0f278b8a9be5364d001f4fcd93c65d8bbd2fc4ac3bce8101e9fbb19a2999a36ece09002d18bced064a619c7193679586e5f35f437895580a6a22398613fb8efc/download ("Timeout was reached")
    https://itk.org/files/ExternalData/SHA512/0f278b8a9be5364d001f4fcd93c65d8bbd2fc4ac3bce8101e9fbb19a2999a36ece09002d18bced064a619c7193679586e5f35f437895580a6a22398613fb8efc ("HTTP response code said error")
    https://slicer.kitware.com/midas3/api/rest?method=midas.bitstream.download&checksum=0f278b8a9be5364d001f4fcd93c65d8bbd2fc4ac3bce8101e9fbb19a2999a36ece09002d18bced064a619c7193679586e5f35f437895580a6a22398613fb8efc&algorithm=SHA512 (wrong hash SHA512=639526ba1271b833beeb026311a3d40d2b50b8480ce8e938e87ea0dfc9c84e76867be09043f9b15fc5b21d003580c6169f1ba59b2202686b80258d8993ab7a09)

```
file( DOWNLOAD
    "https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=${jreTarballMD5}&name=${outputFile}&algorithm=MD5"
    "${outputFile}"
    EXPECTED_HASH MD5=${jreTarballMD5} SHOW_PROGRESS
    )
```

**Comment by thewtex** [comment]
@hjmjohnson how was that triggered? That file is no longer used as far as I can tell. I recently updated the JRE tarball, and it now mirrored on data.kitware.com. The file is removed in this PR: https://github.com/scifio/scifio-imageio/pull/65

**Comment by hjmjohnson** [comment]
It was triggered by trying to build ITK remote module 16 days ago.  Perhaps the ITK hash that was being used was out-of date 16 days ago.

Hans

**Comment by thewtex** [comment]
@hjmjohnson ok, thanks for the information.
